// Mocks generated by Mockito 5.4.6 from annotations
// in tasker/test/features/sticky_notes/data/repositories/firebase_sticky_note_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:tasker/src/core/encryption/encryption_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [EncryptionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEncryptionService extends _i1.Mock implements _i2.EncryptionService {
  MockEncryptionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String> encrypt(String? plaintext) =>
      (super.noSuchMethod(
            Invocation.method(#encrypt, [plaintext]),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#encrypt, [plaintext]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> decrypt(String? encryptedData) =>
      (super.noSuchMethod(
            Invocation.method(#decrypt, [encryptedData]),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#decrypt, [encryptedData]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<bool> isInitialized() =>
      (super.noSuchMethod(
            Invocation.method(#isInitialized, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> hasMasterKey() =>
      (super.noSuchMethod(
            Invocation.method(#hasMasterKey, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> deleteMasterKey() =>
      (super.noSuchMethod(
            Invocation.method(#deleteMasterKey, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> exportMasterKey() =>
      (super.noSuchMethod(
            Invocation.method(#exportMasterKey, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> importMasterKey(String? keyBase64) =>
      (super.noSuchMethod(
            Invocation.method(#importMasterKey, [keyBase64]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String> generateProjectKey() =>
      (super.noSuchMethod(
            Invocation.method(#generateProjectKey, []),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#generateProjectKey, []),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> encryptWithProjectKey(
    String? plaintext,
    String? projectKeyBase64,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#encryptWithProjectKey, [
              plaintext,
              projectKeyBase64,
            ]),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#encryptWithProjectKey, [
                  plaintext,
                  projectKeyBase64,
                ]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> decryptWithProjectKey(
    String? encryptedData,
    String? projectKeyBase64,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#decryptWithProjectKey, [
              encryptedData,
              projectKeyBase64,
            ]),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#decryptWithProjectKey, [
                  encryptedData,
                  projectKeyBase64,
                ]),
              ),
            ),
          )
          as _i3.Future<String>);
}
